---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: semaphore
  namespace: semaphore
spec:
  interval: 15m
  chart:
    spec:
      chart: semaphore
      version: 4.2.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 10.1.0.115
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-tandoor-recipes"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    persistence:
      config:
        enabled: true
        mountPath: "/etc/semaphore"
        volsync:
          - name: data
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
      data:
        enabled: true
        mountPath: "/data"
        volsync:
          - name: image
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true

    cnpg:
      main:
        #mode: recovery
        backups:
          enabled: true
          credentials: s3
        recovery:
          method: object_store
          credentials: s3

    ingress:
      main:
        enabled: true
        primary: true
        required: true
        integrations:
          traefik:
            enabled: true
            entrypoints:
              - websecure
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: semaphore.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - semaphore.${DOMAIN_0}