apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:xeLfUd7GVUBOxoR8XR5nuhqaE1+Q7izfpx4m5Bv83zYZ2ZsYOs9OiaKtbO9E5XsTx9SfzPP45PLWO4aupQP2GYI=,iv:ceHRJZJUJLi2PeKhuidwbQcedZJL6F+g+itokYe/h0M=,tag:0BYU8PxrNUaFpthk42SowQ==,type:comment]
    #ENC[AES256_GCM,data:DTCQTererUR5mpTFNeZU8737Kb6WSbPq2ksh4Q+RiyFrOEjfZWCjuUggGk0=,iv:eaZLOnnlMnIagXRl1be4ppZrGxr15DWY0KU1Ef7QYC4=,tag:237RjH10Ve453fn4fr0V3Q==,type:comment]
    VIP: ENC[AES256_GCM,data:MB347a/Va/klDg==,iv:zrQTnnx8v+KLGQklL4e2zc4RaR4Y4zZI9mzgnNtUUfQ=,tag:UkMYgFnJ2FW1dVBPlSCOrA==,type:str]
    #ENC[AES256_GCM,data:ONpnnfzwskiaAOoY8E6rLcMELi8eSl+T441D,iv:IAbqyo4zYh7Nq10fnsxGxNotSxXJ13GCZ/2c0nzLLUo=,tag:8ObMw8Zmkri6hVy/mxigmw==,type:comment]
    #ENC[AES256_GCM,data:fUGOcKSyIVNwJtMZDTXPXrX8hSiyayzRrQHBxQPhN6uLsrmFRPiJcJJBh2W4RcvsEqtlj6doQjeVrCxLLCNYHfvASY/cqulQaVFm33fEEnoPGWjOpkB9ho8=,iv:OQHpoUkivXNgWdjina+TjE4s1Kz9k+KR/FT5o9bzHRI=,tag:Z2+v18ZeX3lODRORS3P+uA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:CrCGW7SNclbyyA==,iv:kusHkmD0rmX1/IiTRMxEwFKMTDTJCFbGtTz+MZ8CKmg=,tag:yo/ROIdAz8H2kIy/bBRn7A==,type:str]
    MASTER2IP: ENC[AES256_GCM,data:UeJPfWwtiFKgug==,iv:vtMdxpkoySaHd2ZQOkqT9mYBVbJRNZLJOstBt1LCPnE=,tag:ArfxGuMwxSEXY47qpTVVpw==,type:str]
    MASTER3IP: ENC[AES256_GCM,data:lfKdGQbv2iXU3g==,iv:V/q+KN1kwmaWES43znF+tUiuPeXruETjB0AnzKeLGBg=,tag:EmENDUjgCrySa0WsNtWCEQ==,type:str]
    WORKER1IP: ENC[AES256_GCM,data:1J1ZWI1P9mUIog==,iv:tnsqjlhI44SJmxgt4cPkNGiW/a+tgXxr58LAApc/jEg=,tag:ZHFeWyBBheGile5Gg7czgg==,type:str]
    WORKER2IP: ENC[AES256_GCM,data:LX+eRWhs6trw4Q==,iv:xlafFSbeJPRoSSoCP0Nwl4lT0P+rsjO9rjiwaHMTQrY=,tag:77MQDOV37dOtPGz8bK6DXw==,type:str]
    #ENC[AES256_GCM,data:NRF62BsEKLfmRTC8m3+Mv7frKXfjtfEunLNq9p6CrHggIg==,iv:qe8hcdtqKXvIqT7TSFNF8dV4xmMZNOtyilgNN8necMw=,tag:xcY0+ws++fgKHlcoeli5YQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:8CMwUMkDoHk=,iv:gzuAkUNjeJ0EDvlQwiSuudZgT4u+qqhIqlt/9ossH0c=,tag:No4sPiXgpSXLdezIXQcgIQ==,type:str]
    #ENC[AES256_GCM,data:YKPtstuJX43uRLyRCXAwBLOCIswLXHCKXnnjakVbxKpr0vXBshFqR1kCp2YNFcc=,iv:g6ViwX2eiuLVMGeorzmgKALcaQY4ESXda2VzVDza+88=,tag:HKn3rH3Kweu40UcUe8no9g==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:qSYl2itecXgkI/WVdujHiNGsnFLv,iv:vbC0zILCziVqGEoSYir6EYD0GpSZrhRGWCwxHNovAXs=,tag:thKYPFiNYfjVCXkgfuXMzw==,type:str]
    #ENC[AES256_GCM,data:efeRR8yMl53XaJXvwKmK/EMRMdz+JOMlv2jftPlLRrPvzdAHYYFwj6dG8hll1TpoE2z3iRfJhaeILbYbZ7iVZZgKh1EtPBD1hR87Gj9VkWo=,iv:fbkEaP8VcVAJ5uDS9khcHW/pw5WaAbDF28chaGS2MNM=,tag:5X7bE9PpqiIGPPECgl/Qhg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:nFph+F8NVy+ifA==,iv:vH4/gE7aOSnic3Q+ApouIfcaSkS55LyH/uegsuw8GVk=,tag:8hvs8iMhwtt0jN1Zoyc+oA==,type:str]
    #ENC[AES256_GCM,data:m5mBhE/Iiml8/Z9ucH4JMw2RuLfeAFh2nrxX03cqwRZxjRGAm1yYrj2KHydDR7okZDLK2ZgVCErOCA6PYyqepETyuBz1RotQRPawzG/6jOl7oLfXEoYp,iv:SdVlrJd3iXOyCw6iac8nHiw8SPDv5RdKu15DggimV0k=,tag:H5DJcgvni97kFC9Oz42k3Q==,type:comment]
    #ENC[AES256_GCM,data:m6rDcskIu6qvEgso+rP42SgsSCh7yvp4V8ZXLcR8V/kjlS5AXjxmCVGGpQznIqEShwlEdEfTv75ud58N5rTg66FHkJZwc/fPY/CMH3o9iJPjSVj23kSeWLCS2yF7bVn56YoJdgir2gtkPZyf1FM0A33ecEWkCGC9T8PRrw==,iv:KVjU7pNsLOIrUuYQWePVntucxt73/gt5cRMtkWDVhI8=,tag:DznaRKKzLWYgLLLFd5dn8Q==,type:comment]
    #ENC[AES256_GCM,data:3VG5QjifnxptJZkiPgqpbEdW0+gRA6IHYzEjo5YtCRDpwRNQ+rt++g72itTeN9rKfyvocMWWydAh59NHQ/OxW3U1+IJBRhF50BQxhaJd67o=,iv:jkDNwLtctlosrhJy3vNNLe0gOmRlGmRwCJW8xBIhhgs=,tag:B0gs/F4DmDt2ZQ8PFFc9iQ==,type:comment]
    #ENC[AES256_GCM,data:DHn60ervmscRLmMHWDF0nrWirZDRiNis+AcrIcPNeClw4PBl7WIprgOD1Bq97bxwMZmLnvPb,iv:+PttF6k0d6DsLDKcrk9bKgz9xwDeZ6E1PgeLFr7LCNs=,tag:Y2q7jVWHQ4HmisXPWzyfhg==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:+a8zWHItO9QaH8QMuhg=,iv:HqBEXc8lllWugff9C+7k/DZm3xmhqSvHrxCsE0n5g7s=,tag:YmO/azAo0bKhBNtzixRA3Q==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:CFyYzN1nYIwzU1ibUf2sLNQT,iv:HaADyC7NdotYsA3BAaLHYdP/XQuUJ4IIZuj6p/KjHxA=,tag:90dvdvDq2AZdOF0LJPoCCA==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:/E8lEHMEqGfkbd80qzHt8cC6NeMKFJimhLdl6OxYGrTUUKbgH1AJSQ==,iv:9fLCGNotvKnBLMCuxMmOZvJ0el83hiTlOscTe+uH+hE=,tag:Ei7TFhzPtt2nzXwrNmTjHw==,type:str]
    #ENC[AES256_GCM,data:sL9kDgXZLTLEeERMzo/AlPJ+j2emZonqkLxWMG6M/hiVVJL6pIPk21iQ6M7st4t1iNHV9qfBhlA=,iv:8/MyrmKJ+2WTJfatHbBoIQJMAcIBYuxTQIrqAtlTF5g=,tag:Zcw1wtxrJkMmmy9HYgO96Q==,type:comment]
    #ENC[AES256_GCM,data:bl1p8PeR9qUx4owTA6825h1ku9Ic4F/8Fg==,iv:wbV5zVWIZsbY1OVFd3KIr6+b+lQcLjYX/wyY3J3q2Q4=,tag:0iD2H2IfO45GT9CgYZ32NQ==,type:comment]
    #ENC[AES256_GCM,data:dHYIX5kweo3P5kh36OlQe0oUKn7Us2KsvrCyfNCKJW4Hu20ekV0DW1Eva3bRbKvs7l73YkrT0y9R9lQDB8jWL3U+xunbiBGgpQO2sjU=,iv:MYnuYYh+ZnvL8ztJwvyX9enWQmYLNa4Hn6qk5x5zFQ8=,tag:aGiV4PE26wQLgFVcjSgT0A==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:ZJN8MJR3qPG88dtMtPAe2cryhw3LwP91qb2jP/4kcgMYgon5gojzWVsxoREQCZ0hv1RExX7kWQ==,iv:MBv/YT8lpuS0JPkYUqAgyF309jywDaxWXukArx20Auk=,tag:2LVmuvMlpfiCgbIbNqSojw==,type:str]
    #ENC[AES256_GCM,data:NzuQ8kAOe9Jg4UV3mmc6rV3zDcnQkJ1A0wDC7PBy8cBE1YcUU+eZ4VzioAYWFoWHJS9lVdwI4BBQHlI+XFXGpZTmoM2AYnQ=,iv:H2DbB66mDio8NWvjCRVIkexm1yPouU8qxS7o5BEHo1k=,tag:vatWpPqjP6Z0usGVi+/Gwg==,type:comment]
    #ENC[AES256_GCM,data:9KTdNtxCAGC9Y5u52SongWX1lr91an7O24GD9iWC4m6vIRS/o6n7dNl5U4eoRW3b76BrcFBA,iv:Ezv51PgEcb5RBM5i4QUoIR0nuea0Lhw+jEr4vejs05Q=,tag:cGp0LGB1lOJX8qGJhdbvzQ==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:LkL3cWvIqmox/rQFVx41ZQVu,iv:5pXBpqJbY2XEfcIpU6e30GKVtRS8ag9TXFVXuMpqw7Y=,tag:cIespH5Z6vlXZ2XOvuv9hQ==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:EF+g1wn00TuxfRBn59G6/iiw/iw=,iv:hT6Es2PXnMQsTuh2cep9VW41uTdbqpv15czgbERfhK0=,tag:GL5rbGuBcMKqFw2ZTwvg6A==,type:str]
    #ENC[AES256_GCM,data:bF+5/2zh98r6hB6hsKs=,iv:WytJhrwkO6WVkoAWbSmB1WGglsTrutUSFvVKDfSZnao=,tag:jVKR8nOK+S6bFWsmxz/cmw==,type:comment]
    PODNET: ENC[AES256_GCM,data:f3heK16KuDd6CISD7A==,iv:CW9ZjNc2mJoTxgG9CY6vAwWk9SmgJ3SWMUS2Q5/MgaQ=,tag:RBB6ta1H6yZz+xDMJIk4JA==,type:str]
    SVCNET: ENC[AES256_GCM,data:9x2bcCl07tc/0xQ4cg==,iv:YLACvxyAB9QckdgQXgvuv/eur+7WWP4NKMeYMIwYSOo=,tag:n0IFNoOQ48gJCn6nfg4k2Q==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:wYcqWw==,iv:fi99ii0XVvEmLRWInEh0EOR0r++Y6Xe2iKEHo6+2Udo=,tag:eq2jAcYlmPw2W+xaacX7Sw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z324taz8q83tl3g9hpt4g6cfv7x8x90c543zj0344phevr2tdp9s9dnx6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRGZmcDQyZG5oNitqMCtn
            WjhrdGF6SURMVFpYQzJQQkw0WnBUUERIZUR3ClZBNERicXNYcGo4VVJNSERXVVpS
            ZGtvdGUzWmVxTC9yaXdvYU54T3NoaHcKLS0tIFo5allxQklBdkZ1REo2ZGNvL1Vp
            eHZ2UnprRU00TWhlMTcvbXBIQU5zTVEKZu+Aum97Hi/da5z94jm8TZzqK+iVnYaA
            QZAVhaTxVcK4cgyC4BdrkVbIhVWyWW3wr7Fshxn68vBKhHVMq3jvMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-09T18:39:13Z"
    mac: ENC[AES256_GCM,data:p4qI7iAVK2EqGxrYBwpTODxyQJSpQd+Xvjf5hlLgxCep551A9GV/gVKsLuQEtlfs2xWC12ZInWVwg0cne8Tw9mdecpcPdGicFoACiTxE+AtjCx402YapVPAw5hpCJ+0RMRtkrHERSB7vZL6yLMHN84hLCbCau/Zost8ZzCuTHuA=,iv:liXsCBdzLFjcbrMpZngWFMnTVyMYfJF9lTCIzMH30j4=,tag:4H6a8CxNnszggHhrZn/Kyg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
