apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:a5i2yMy7OEsLSrTvRxKrRVRMYcnIB3x/6p+h1Pp7kp/QQQ4xWXUlZkNs4lOgyuLp8sasazuI0Jy+VX1xchQc28ZntlfI4G3CQ7hnSYnhnENZEyj7y/L3q1MXE8vMRIJYLhK7EUpBXO3Yc44+76xyzJ6hzq1wXfczOyg6IjyynhPFCVSO15g5pkJMO3tu9+I0ssz3ujLXVCY3EfUrH3kk0uhVjxK8PtxJw7ugvW6tSJBMY7qrWPb2Rhe/y7Vmrr9z9dZ1Mwv3Vgrc2z9e2h/c+r0ruu+qMw4z2Q6gXbQLOIOOsuk0FeiffkScSDma7UN1/XYInmTTjV8r1RyleAfoxyaZ6fa3DJ8qR4uMGxvKm2jPdWE2w7l5jXYNaVKRgBA5,iv:8ftPCrQqlXRWdzP0RG8BojecxEJZh1UY1ISD4AZryiY=,tag:UHypb7EsFjaIYyos2/4XGg==,type:str]
    identity.pub: ENC[AES256_GCM,data:SBWqgNIrbQHBww6OIbsO6DWyyMrFlZBvblV95HGyZqfwn4WwJU334ImbwBofHbWg9uSfwcEmH5BJVoac6hkXT8ujXNxtMP9Z4DzYq2pXWl5GoIiiWYv7pUjPc/ZQSj73+nyHQJBUPQlxrkNtHSHPC+3GBbKLteAxmOcWdy53po08gEgLGEsl68Std9NxD+nfWfGL/tjszOvyibF3rSBZa1DNRqWgvIeZDrs5NldIQ7Aojxyw2VTzjNgRI+obydS6AYUzMIghCVJ9spPsnA==,iv:yKM1NtNqwg7cEnfYLD4vSLHk1PF3ickr2mjgQV+pvFM=,tag:TsYCFEU6SbdpGlD1/9/x6w==,type:str]
    known_hosts: ENC[AES256_GCM,data:oRrlh5/LYUNgE/yfKJTZ02BvQlOs4lnn7g5oPSZkcILHpEu+Mtr54JVu5JreDdGEB5d1bOD4yg1BB+kyCAVUwST70aaO9eNXNFtubxjLXNga3hoNI+S1TJtvjkV7g7y+Aio8zLe43qeD2Vrvrn++H+lZY1l5Kuw+IOkdnCxN0Z/qghbqCnP9+gL6skfNQqfT2K4IgkmbsaR1NN3aAzxHwsjTkn3Q1lrsXRKI,iv:+ZjcwBPdvXrEhgODhRWssgV0YOsrkDLvDnw5LBz81XM=,tag:tPTxjknuyr612o5hR5I41w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z324taz8q83tl3g9hpt4g6cfv7x8x90c543zj0344phevr2tdp9s9dnx6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNTdNZEV5OEF5SDgrTTdu
            ZjBrYjArVFdCdVE0NkJlRFgxZGtFakR4ampzCkRzd3FjM1RYYVRnT1BnVm15dVRw
            VEQ2clJiQWRZUm9idHRRY3JCOTZzaFUKLS0tIC8xN1dZTHRVMHZzKzRVTUdpbEtW
            bzQ3Zk1xVnBvS3NPWU4yQm9ia25TZ0UKVc5abqNk77MdJbt9voll6A7BwLP7bOpd
            jizWfYFISuZLTplMScham0iXlo8gXBFqaVAcWOZnDkzvp7Nx4WjQAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-13T08:57:16Z"
    mac: ENC[AES256_GCM,data:fr4wz9dKOAFCUzxoMSDdjGvbS7eyeyn956jYLOjB5z9MLY+4l+loRf5Ead8uIv+gS9rMaiJb8ZA0mH3zZrPy5wOlw58q+09vkonw/AhtkH4RgC6UYjT3fKggRYbmYplNi6Qwahhxz+CtusMik5KJ3/f4H0yH7/hD+/LvQThI/3A=,iv:LUB9wg5NfMZR8Noh1AfTeXtmwUpVjyHfELQbgYCpPs4=,tag:P9GkybTdJtMc0J446yZGrA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
