apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OGtVV/IhnDSaliv2iYgbwlwegoOHi2375/brhT5+iXRZEE4j8YknV8UCNVqx0DiKUPQbdmmdX9sZ+rH9oI6qCY0y5QKavNMFTbUlj9UjW4k/vJL0c0HNcJZD0Fh5yoE8ftYLLaebNhLV4IYTASxpKlCnpuGbgYppCv9IcmRdaD+95Rv8SHroqeDdnVaOBeFkOaciOyVwUAjiSXFsA/WjZIL7zrs8saHp7OkNq5GXaWHSGDgkp3IGUOCJZHkIIC1oardBa+UMhY9krxloNoap7zjI4Jc2zJrM2eGwgKwRflUPGzeowpwp4jObyWkqJ7BzIQticE47vberiOaMJBowmSOYw8eS+fQZXTInkgbxEeOhQOMcjwZsuqWkgjVZRFLN,iv:f/XreSYEtBqYC/hVKddbxsElKYj+MoU1ZSOd2l/MH38=,tag:0M4talo1yubPAs3Rqvj88g==,type:str]
    identity.pub: ENC[AES256_GCM,data:x8YOiGJdtZQGzE8bKW/e9RrlNOSfB//oavafASiLE1wB/YL6BiXAMefR8/ACPQV0z1YaTyEix01KSx0h1FD0oNaGG5F4eCX2bfGhxqekW0oqQJTL1NNXtaQkfvpWQnuOrHnMEBfvzVSkXBNTO4+ED7vQC2cUzm3YMHrYKZXSEc8bE7ORSfhlNdx1NYbLgVuAvZOpD9VBEJ3k64srynklE8uOkNZIJA14lyhD0gL588t674ZJ4zwhzEC6UOWlzS6JWkvRwKTQMAC7IfJQfw==,iv:2QzyJBxaMDT6ymJt2HXqxOnMvpUeZy2J/XbF8G0yo8g=,tag:bQXmLPkTmQNOWZwUsXFoQQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:0LLpx9TigKCAdbrOhJ24OyFbWObjXAAd0s92YtyoSaNQgU5NZqc0/VD3o/eryjzzsbTGYPXmDoZtkg62HqKCCv4fPnXnPjITlnRAEQ3FHP5DyebKVI/YeDDQLgVSfc/oH3y7kFWh/wZY9JqHCrYKG1f5+zh+KHRRwrgaa4D8nGzJwVS1zxSGwl5WVSahdggpo6i1LT/KKM1cyDMXeBN6E1CtzJQwCXvgEDKn,iv:E71opXrz5HwQmwsRmEQCDsm7gzOvLU3dpeFbrtesZ0s=,tag:KsAPrE3VdGb1Snk34Hgtdw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z324taz8q83tl3g9hpt4g6cfv7x8x90c543zj0344phevr2tdp9s9dnx6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDV0ZHSXBxNmRHdmxaOGlR
            T1pBaWRTMVp2RVE2QThxS205M1RKWnpwYUdjCnJEbjhoSmxrNUpUSGdMam1rS3I5
            dVRuR1JuSElpK2VlUjYzQ1dhYW51UGcKLS0tIGQzK0dkTjhwdzYrVDlSVVo3SHUx
            UktRb0FRLzRHT3NYZmttMFNNYVdjNzgKzoqTcf9dO4MV3zeEa6rv1mYvDe6jrskX
            E31Uq2MLgX+cHdbicTJgdmqNtoot43hme+EUuRdTs/y2Uu6zV0LZYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-02T18:15:05Z"
    mac: ENC[AES256_GCM,data:cPxTI5IwlShBMcQS4k8yV9TfpntzXFtpq6ZFTys+Dy5yBmz3H8nFin6ZSZ6AyYzANQUa+vSv2yt5IsYklNGTN8qdxpqJVzKE5hn2+KVfwo1WPJsWFZQMtCpLciS26m2JFd6vZ9E8V3XE/998kebkvpPieU27ksrJ/gMjx9RQ8Q4=,iv:mLzvXDUa9Tpav7+YGpOX3+XLiJ58Mp7Cp8YF0bH5T0g=,tag:XUffOdlEvHDfQTNDs+XVgg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
