apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:CXkV+cZxO9YZ6wHzdd0SwOZygsUgNKJs6K3EzfRSV0zhi5OlMRXYM9Dnc/G2I8fixcxbvmYf2S13xfNOQsARmBpSK1UTEWU0bfqj6YCUtdiRnFp3gotRcNNNQBzv5xfmXoiu7av24v9ok7Fkk54zFN49taqfeR3lDN6wq8YYK/t4x89lH0E9quzargw366rOwjlx/UVPu+avN+RfsZzDpw04psZ+NDJS8kp+mWxSQFOccH6i9PHq/WPKEEyIfF+4Y+G0Q1kUHK6j4wjCywnkbDeQBNLLAM/1dZG3X3Ctnzf+TpxtmOWkVT2M6yK60fxVaX49bIkyZAolOFFaqmFutspLJm8ALONjV3W71dToEmzvRR9L24z1wj1TbvERQoXH,iv:TLQdC7ExWJFnQYIjuMChT/Q9cFV2x5StjEI4zk+GNtE=,tag:KrPfdqqI4fHk/wx+OlEoDg==,type:str]
    identity.pub: ENC[AES256_GCM,data:M8NaMNlG7N8lux0RvEDkzMYR/4MejYIUyIOJTjG45bH4FetBP3mqsYsf48U4GXcBh9MRkp4AmeikhAgLkBJQENtdvFklBs1Q/4LaaVkRvaQ2MycyLCA7RAdx0x+7E46E6LTS7ABTU3A9kqyfPEkxxZ7o7QIyk6dhiQm/WLOtVo+p/2FxKOGi7qLS4vyXx9KgNMT5vCuhP9W1cVwyNZFCNxL6zqygbNOBkHdQ64kFthB1h3+GwGSZ1nQlJCuBN6+I7zEjhLw0x0RgIXU89w==,iv:DCwbFvCrSwaviH1/KEjfCkrt8qpAOF/T7uSe7bajN+Q=,tag:uSa6D4rdZZ0G5uy+8Y2dxA==,type:str]
    known_hosts: ENC[AES256_GCM,data:i7eAVdmenT6/eLHUDr8gpigcxRqUbfqYVy1qn549P4h08n72u/YcGS9ejB1X/YvR4pv4HPvpEDorA1IGjKf2ToZpjqMCNuuo3pIWar/TFhyFieviQ4kiruLvwd0FaYYMM7M1zLs2Knpk6tH+QU1odpwQNe0CqDU7cVuC/vXbskKBZrmXLgEHpcLbMerS0yUtDrFzJnqNlyfTouMe2QDvfYBFqOqSg+7TO9tb,iv:bzNe/bDEH6ciQXofSCMBSct+TcgC6buc0nH4/BE72DM=,tag:t+cALcOzyjdzsDfQMJzQ/Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z324taz8q83tl3g9hpt4g6cfv7x8x90c543zj0344phevr2tdp9s9dnx6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwU1gvWG03V01RU1Vaekc3
            UEpyOXR6RVFqV0F4RXRyNTNveEFuejk3bHdnCksrZFBiQW5oMFRWeDdhd3l0N3g5
            R1NUOTVqaDJhMEk1amtWTFBTeWVQb3cKLS0tIE1td3c1RUZiTytCcmw4bC84Umhu
            VmFUU0VMNnJZQXBZYTR2YjlJZ3ladWMK4W+0oZw/jS94c+FU2dzBcPCo5cp6avZV
            oXGsa9tgja0FVD04Al0zdP8sA5aEH4kadxogQRFgBfbtHETD/cz9dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T14:48:26Z"
    mac: ENC[AES256_GCM,data:cNyLJpdvowE23zsJC7FrzPFfRxymdUbfeifknT1js2SX/zT3tVmAeVJMjHfzN9sr4iN8vJ8TWTdFGTk+l35BbgAZU8FYV3kmRQKur1OhgXne7NXvRjZCPR/OvBd/5C/rO+GYAoRsXngDkn9E4UAF071QJw5jNvfv4ROgrC51wxE=,iv:ONaGGhIRrXwwVImkBTKRMeQC5PPUpjEwSVyJ3OlqLhk=,tag:TBHFnnH9kn4Apn5i7MtWBw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
