apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:R3SnA/bfxoITBtkMhQDUpgfcssBwkZ/JyaHnWph6j9hHZAreF7V8e7NCaGI6IshYsKbPsRoEIkKfa518HCuYCvGJZVbqGFEwRLKU/xhdqh6DccbVRKYRKtqmEn0VQFUbmeyaNKrek4Z0exqI6Wxvwkru0c8aM/+7ioplBRR3VPu20tiHxNNvGg6WXudo+NUsFCccyyUH70cFfv9CiGH+u31gL0Wnqg0TZiRHRTfxiS4TYWVloKqr8diGwuXU1nmaoiEMpOsdtzcBSOHkWfJiwEp0hwti+mW1Q4chTdBRuC1O5kKX0D9dBbKCtO8cq2hbkcO17sFqFl8el5JPpVpnt6UwOQ2zlDHiS3tHVcsOkigoKBI29edoldfwjUXuiP/q,iv:mysVqkbpuFL8jKFSdNeg9caTmCszXws970g2NMUsFa0=,tag:zZuyUoSjDzaYb5Th6iSVOA==,type:str]
    identity.pub: ENC[AES256_GCM,data:+RADNCjz3wQSLvInLLjC/n9oTYpT6jCkarX8X3xzmhNWgyXPGqtn5eJ2sjk2GCXXudweDYtwx4wAd6JVcWisxVeFv6HXMiR16qBYSsmpYZNLWQ2/d2INDj9PzjWrIsvbUf4FLfTqCALUPbznX/ZF4YH46XNRftRokM5KazX7ePXDwC3/qY+GarR367sgZuCTdd3zzlDRtXNFqGxBezj90pKFv9Do2hkadqdDw5/AEKH7kuLch/C5wH6LBi0ETvx2ZWzfZTUM7qJuCD+75Q==,iv:pfAynnHv6Q0dGj1aqTPEJdH+0Ofcn018LJN9QNkN0Rw=,tag:20iKKG3q45PKr/Q/gsv8Ew==,type:str]
    known_hosts: ENC[AES256_GCM,data:SFetThD6U9IX6czeaDuMbZ4Ow3uqYG/iBQl/E+620LfRjtmCsTrkd9OMrw6NUxSvdUU78BAa9kIrqXXpfpbdCuB0I/vhRVauTFOFl4MRQCcf2Os8hOLo5mD06oBz4gMgQIlyMSpg92xwE0nN19z+arFb6uv3Wc4fUok2ASZStSeOhj4RtJofCNWb4pbPWG+hYdCL7aWnDFjt5YlTsxpc1sf6zB3MQBVhd+LB,iv:ngffd+X+8+4UwB2SmSjjORSPNKADJe1iotvnDHJEsEY=,tag:CxPE4KqYV5YyWz5EVZJ0Zw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z324taz8q83tl3g9hpt4g6cfv7x8x90c543zj0344phevr2tdp9s9dnx6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQazJDYWoxaDFxVjRnNk1h
            NVdvdm9CUlN3YTlYQ0svckYrcmdOY2JqTlNZCmcrTlFBc282aFdOM0hzWFV3cGlJ
            ZGU1N2pNQW5nS0M2aTVlckNjSE9RcWcKLS0tIEZ3VkRjUkh5UFlJSEU5dXJtc0dT
            VS9nM2RObUFxbXo3clYraXovZ2pwQWsKqv017vuHFyF29dYPYXpmtQF7krrbRxsb
            N1lTijh+Ms9Df/7U5bWL/twsFOxpYqJbwDLVMIQh6Vj9v8q8eILkFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-09T07:57:28Z"
    mac: ENC[AES256_GCM,data:FMM5TwSCx14vL2sBnaa6ueg5maT5jA0YWC+FAla7eMfLQ9YH9ddZdNHmNbR2gjMAqw7rvOQMxnSE8jCNkSApTmFEoisPCWSzL7TNr8cfnl+WZ3snM8cP9VRzQk+DLxn1LGf/deVcwDaeuhG1B4/4koKOjS/rrssp89AhqteCJmU=,iv:o1Gk67KRFkeUQqdJvlhU4v3XTXy4fB20NNx4mSm5OZ4=,tag:jcU7LP0SlIPmrgr7QYVjHw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
