apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:oIdb7nmGbyLF6Q/JScgon+LP7X5ls5MySP595S71Cgc6x+78qFMy5Ys3a3h2igFQLTzCPcFwZqmPkDcD4fmqK2pQGZ8OTaUcHzgufnpzQtDiBYpTTbtHaKMGeJgObB417fZTB9LQWpTl952Oi0Q/wmTtyz/I1cIomzxPjfMjPI70uHPmz7Ca82Ba54B+GWCgXCWv8Q1QS27p6WyuVQJRvfqYVTybOdn0ZWOQ+QHDYMKZPcJykSDLNzDZBkMi0fDtAVr2un7GiEzFBYkWX0phNPTShgc3xm2ytlFOd+dZxy7Ftc8zv2E8sG64cAUhWYL74QoLnC7z1ISiwFbxfSYEQDUKuJL2c3Y4enB5T3BNV55oW3dEo2ayidXbvJxZ1auT,iv:HHlecJR4daVg2av2qIZRtbILBMWdAjGfzCeMUH2eXS4=,tag:o3MaCIhNigdc9X66SXOTqA==,type:str]
    identity.pub: ENC[AES256_GCM,data:mNEyz4yKzgJIAkPZ7E9DNSOgrLTM7xQjQzymmjvBs/iqg5wwRltRq08x45tIUc43IfnJtmB3EE9j3AvfklkFCOPvDU3xqVu/Zwc0b1NIKVyee+NPz9bCKN520HR1+fLSuMpfweFI2qJPRGx9rVSWm16l3hbmvKsi7vv6HqP4fZwgqU2KtElXay1UPFIF4DUU7FkA5WiFGgCBUrq+8HVGYoWov2mN9QbxPM7yw5kDqNHp7IG1GOUYMLEnDVonXS32xjDFdWvt51nhnzjrvw==,iv:ow7RpFJ7lifEQlp+P078XrmNvMdQtm9zH+lQ9mif5XM=,tag:oU9sdAwkg8IpFkeQqxdj8g==,type:str]
    known_hosts: ENC[AES256_GCM,data:RgvF8MhMVuGUskj1Ze4bhrqNcxaffQcEnrWhYZ+lhaVM9CCiu4BGisUsOH9Y4Vpuvv4r5XcEfG1vWkOV6Qf7ARqUyqpShGzxu8ydVnMx8jPJp816+/4Z/hklpoRTnYjPMs00lZHUWVu1xi6QBD4NvXgATBWHqehhL+FEd8ue4p9kcqdktriLsdTiD8UaNeO/QpsDsfAsQ57cvvpgQT8maTZcoyDaZ06eTVp/,iv:7Bw2S/mVEL2upyxPU4xQu8z14q5wWI72HisAYDBEMNo=,tag:CWpiuZbdPMdqgkNRRxi6ww==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z324taz8q83tl3g9hpt4g6cfv7x8x90c543zj0344phevr2tdp9s9dnx6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSGRzc040RmtwQnc0V3Ru
            NndzVEwwMlBJMVI1NHlncWovV0RaOTJob0cwCndEdi9IdE1senkzenl1cVYzOUlr
            ZVJuckZtdGhWb0pscHVKM3lTTDIyMGMKLS0tIHd0RXF5dEh4cExFa1lPSU1qNGh2
            dnpmMkRlNVZGeTdJcWtaOVhMcjZGblkKMYn3NuNkwJ4Jxf8A/36LlPjP3j9dfBsq
            zQ4GLbgfUtTWEx1bozwsXEg+UOWxMiTyVmQ0E5pvv6WnMyrqi0m3aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-16T10:23:39Z"
    mac: ENC[AES256_GCM,data:1eOXRbmiAIKlpRzSoPEDn+LiK3l5rtoLxAOY/nDqVPFZKaWccIT1dW3avYuYikHxOevjGo9JrBM6fqTXJux/UCY19Y/A0FXROd/XstHguZfHAta7sOkunEj/3Ex+zdFH143c8B1cpshGVwtAotXqMqzi8I5XYEBzpga1iX5icS8=,iv:OCOQH0JE6fOTj7pOF8og5Y0pISIMinoixMghg8KEIcM=,tag:U/qx0xhe/LuzHUeTaAW/mQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
