apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jws5n2Tf3rg1cHh/aRGoYUXu72dtyyg0edfTuGLd1ugJejgaPjWNNGNOR7yQZ8jegpXxsbIn7XroKUl5w9Zj40tlfQd5r9/JopfImDT4Lt6TEBU/7nq39vhD9PBufeC8S5lalwAysFIG8hkkcjeoyNuiXlXlJzHKnVeCGHofVtkOFz3TTh5ryDwUvaKyGQw2Qe8EWspSfxsFRLxJCgbw3gDWtSuLilZT8hzXi/OwU7cDw+6+/2FpZxawno11Ux75lEy04wJikt0xUeOAWWA34ZzHLW1J37bHVUpQpfGrO44Dmh4hUhmCj+Bftrv+ZdekOzGJXUZJizdDW9xi4NDNulJ2U91hV6h94dkr7j2pPohBPEPfwf/ytglVKbpH48D3,iv:utEkX0O15DK8x7Js6OcvqdY0Pd28+a00y6pDvG4ie6Q=,tag:xmKtzJElt4riSZi1hq6WQg==,type:str]
    identity.pub: ENC[AES256_GCM,data:xbqckr9snXlcGKERKylpqH+e7Ajup1efxJFNPCwFhoBSWtGRO36kr0X2TmngxIomeZQ2H4+gAmmGHWl/byxrdqP7N1UIoXVjxur4KgAs9bzw6NU/50ynVzGdWhdOrpO5RvDDX5dskuMuBu3jr/iFqMt8FlRul2SFSgs8yLcF86e/jnmCXzla3wjRLETfmczTDRYoC5SIaHd8N5GH/Pz+EbNGQKsmjQjI5w6dWFPaHg6HzO6wJ02+WznX8hpqM9xyPUyDez8M5Ujqw0VrDQ==,iv:xV9aFGN9uin9VhpEe9qWdYcO9FEgy6xFiAaVZVltdXg=,tag:+mtZdDb30H+9njOi2VXDcw==,type:str]
    known_hosts: ENC[AES256_GCM,data:7j8LPQz17+X8XR7573ySGIDtewPTTK+Ia5i3/Gg/YBygMF7WOu78bYDYQE5Racr0QOhI/yzV6EaFJxIAzmUVJ/Aexz6GqMWOWMcouEU07FMtGjciFJekVhmy1xYDjRT28SFVyXsypptv0wTqxsot0ayx4+cajDnSOrs6MosP64ZGP1RajXq6V1AReKw3uRJyVT7aapjnrFKczV28MH/F1J4aTx92wmbIS/hW,iv:je2cdQ7Ia4p+mBgLGAss5PJy6vEpNOav8MG1dbAQBeA=,tag:XmisdRYRRZdKNm5isoztUg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z324taz8q83tl3g9hpt4g6cfv7x8x90c543zj0344phevr2tdp9s9dnx6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMnB5cFFWQXpPRkEwMW9H
            Yzd2MlhHWmgwU2Y5RitMM0JtTHhHZ3BtMlFvCjZOL0ZLYVZtSjJRdlhrQjdqc2J3
            TlpWN09uaWdPTEVoZk9WMXozeEY3ODQKLS0tIExIeWU4SnNtNWpFRnVwTG5abFlF
            VXpxQkFLeTRodTgrSDFicVdoekNBNDQKxRbV/7cvgJ58RiNW2hLZLlhe7yL04teX
            8/ZQsXtRK6ozdU5B7ikH0F8V4RJs6WbCtkKpeCBMobwq0N8uW+GitQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T07:51:52Z"
    mac: ENC[AES256_GCM,data:6qzcwonvXd1LRiXgMIJoXieM1EiYtu1KDDiv19oYJwz3RqUdGx9ZYWne3n82FGsgzWvZKUZrFY1NhPsx21yc0B0fMWZuLjhg6f8uS8qRF/9VWnrWCp2yFpYP/eTgVyoflfLHkt3v3wvus4gryTd2OrTWsWYqMG2x8gL+I2ATGoI=,iv:YsV/5271jPlFENJpD5K/xLQzPlvSc+ILue2mSmCMGH4=,tag:2KFLn+GC8T03/aP2U3RuPw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
