apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vlOsx0AWEBa3cdf6dq9EzPkaVVR/WGmKZ/QzXRUQykQoWlAl5dwcnUQIL0a3RcNB6luNMv9DFGn5FTdS1F+wQrJdjL+Qcl8vWLoY/VuMNUNQKXxKdZIu1a3v2/jBxOw+3ze83M5cw9fFlDzj5tUqPz/jYpYaadaBYU7xWVKJ/73v75lfH4xN2ImstBNN6H6eJu8cTSqtSDH0f5wYdo5OMwrZLYjWZZJbI1nvoXPY+sZxyT21niQSft2yDQQ0spCUvXsRXX3GY6Sql2zbonyqT7P+xa84rdGKOJBUnvvuUi/JCRWALGVQhLlHgzhZfL0aXyT+rGVM19cgO07MmptINZG00/jhTal0k59e/QE+ZEE8R5tVfZbwdLOaCwi1dxYM,iv:hl/ZbPF2DZWp1BQtLedNmJDZHaFlCPLLGuu2oCEh6vg=,tag:u7Z9hcoO5bsDmVy+Dhz9og==,type:str]
    identity.pub: ENC[AES256_GCM,data:5zIN3euWNRH6rSHSHqGmkXkUd0kfZrYP9E92Uw07KKJl2yUqHZvKIYpopQfLAgOThSb8lMb/WgxdfUKHebfiai9MRnCsz/V/s2821tgxTZmirBPuEtHMTHQxYvpF/iCgD0PLHljXua5Kd5h3hoBDSQ4MePcbiwdY0/QR5qjPPm9ZPj1cuHYLmgVQeHuIHi55E6ps5Z74FPFfLfD8NCgWr77p6nbjHaRZY6UFot8UtY7nACQPHp4HaQcQnnPVx1khYTIY9v6SFNyrf0BMZA==,iv:I97AxZzltsy2tBJdabz06r5T1zv76fr09tTT+Odo4Rs=,tag:eEImDGoovIpGuVIfvjNtAQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZvxiIV5bTqKKHHs7265S6TPw5iPFUJfwyhf4JaxDc7c8ye7KSx1Z/AnK91e7OOqnHLdTm8boSdfDiNgu/1CkGzjpAfd4TdBoimeIxOcUD5NTR11/pMf2FyXm5y43q9r2WYPdUq6fcYwa9BTP2dnPI83veppiPrl1v9LeaacGkHsiFQxex0gV8uEr0Q/iXi9W/zNzvqZZGxGdVhaYxLsHdEU/MRm2I4M18UzJ,iv:xDF7ld3lf2r1fJicwhLtZhsLx/yvBhF6Ygkw8M2+Bkw=,tag:saPalQjtJl4WlQIxx7h7sQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z324taz8q83tl3g9hpt4g6cfv7x8x90c543zj0344phevr2tdp9s9dnx6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodVo5NFdROTRKVzZEUCty
            WlZzbWdPck9sbUVZR05OZUg3ZW9LbHFCOHljCmoreWlRMGpDbTFDa2ExYXFObUdz
            YlVic2FBam5SUFk4MHZwUzN5aE1kNTgKLS0tIGVTbzNwbUFJSFdlYWJEbjQxdCth
            bG5Ma3FTTmVQa280RERUZHZKOUJSTmMKFLmRFwklqCNi355k9DULg3dr+9cr0djG
            iEf6MqsruXjd15q3gYIY1ps9bxaRbbZmgIlTru4Rpk7t+pvYruQiXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T21:17:32Z"
    mac: ENC[AES256_GCM,data:CSYIbmUP+PTQqNhCFWkkuDajPlCLi7DES7h9WwYxwDWtZ0dgYOsbKayk6HaK1JkNMyb3Ioo18bp3rdFhLv91iNZcbVeD2B7+Dp2yrCtUQ3zN+bob/0rUsTVkw/+OwJvSv9uT8xkyquH+cRwFESupR1LvpxVGXGVIRilXLjyoJTQ=,iv:iEpLyGcncf4RSppSrgrwu4uByxWVKVJE/zIqMb5/RdU=,tag:AviK3tUgqIdnCtMMszlwzA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
