apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:eWrKCBV73OaFZRhSVBE60dmFGmv3KM4lpA4hWcIiKZv+vHwScd4XaMhKBEk6Rk7I0KjCJqNVExap5Oiqco5DTmPUvLl40FTUZsEEwxSfFfcSz5qW26WLYXucHSU+fhwsUnzN6zHh1wrRjEkuikdSwfsC5Mj7Fp+MeoHQI0njWF1D6EP5IL/kkE9+cDF1mGdOnokSa2zWUqTTwwO+yfL42kF/tnrDXXGlAifXsJAXzOiLGO9xvKezP0slnN65OiAUv1oyDH7G31gGiQtNPH7vaCd5Wrhf+ZMDRfvkkBo6IMbHZYsaT9hok/LMCSHaOOISN3npSk9Xh/ffB4GXvcjjMtCPvGBry/7nH2oa2jXUXqtslPCOINm/+Smhdm4nkM3/,iv:ub6aHertIKULTSuYJAPYCzJPbBjFvAtBJujXHJECCyQ=,tag:KVWcTqpYuaQgiLqOAun52w==,type:str]
    identity.pub: ENC[AES256_GCM,data:b/vipo8G01j+th9RiR1datmGQV4RL3ZEHckErTGUKig/p99RmgPWolJaM6zIRHqXFuSkH28CX4a3clgIPYKX69U9ox5Lhw61gLSh92upfHptovia0XBGFb1Y6hWl0kqQ9Er289GJ21aLQlFNqISD8F++nKfCJRIJerViOmfSpVsAdyKsfp831/htE4p8vgRVuNIrNf/E8yLFKh1OongYj+POQriMtGYahX0kX3Q1SZG6SB1nzzo3Frw8PG2nrG5S6M/3V76niuw5iZMb7A==,iv:CuOyyTPT9mSL/t1us/bSfv7zNXBI52kR5n40zINZ6so=,tag:o5BDl/oO29Q4mKkvCW8W3A==,type:str]
    known_hosts: ENC[AES256_GCM,data:X8sfiJ4lW2WkHq2R68dV0YI6PeM0g+M2iFTp51CCbwZUnkN5K5cahgtnmppln+ok89xEaeCDBoBIWn0DbEgzaPKwX7RVj+p+QsfHLkVRKU6K1myVhcdNfz/ywWi7ZPFh/m9V3yJoiUqAlcfEHJs18WD6C0uUzZYmvJshDUFpYN6enlQVPIT3oyDdZ+3F6wUDfki43zEJilF17SK1TQrXhEdu6L5BK0GZcanm,iv:ZzentFPhu/Geq3uFR9CsQ9cLtkSz9cngsvjxchHExUQ=,tag:0MlBW87ZzXEjS8zG7fMN+A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z324taz8q83tl3g9hpt4g6cfv7x8x90c543zj0344phevr2tdp9s9dnx6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTklCRVJFb1FQbXRiUzhX
            R29qaXRWb2JZRit0SDVvQkJveG4wNytUSEVjCmE3YWlaZ2FMbTFEQlM3L3c1c0NO
            WmNDRDNQMjN3b0x3aGVKbk5jYWlwZDQKLS0tIDFoMzdJN1RndDlRNzBKVmJhNUpt
            cmtRaWVqZk5xWUluK2V3Y0UyZWdBbzAKnZZBPGIR95iq0Iwy8jc3XeVzqHL8vtod
            Qfn+kNP3tdMEqc1o8uvSihp9GAqTj2BaCTvxQCybN9GfW2xJKhtpoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T12:03:21Z"
    mac: ENC[AES256_GCM,data:x1B8HzIMWvjFbzhXoLQQmmRitl5weRFlbHfUggLk6lrVaQ6Yz/uC7kYKBUv/oWhbu+Wv/hBlUhISI2y6IbNDvfLuOAXaOwgw+BPG95nZHchwZh9o0Fw6NHBZhKfn/JsyOgKABsDCFDGdQGDUA5BAP7mren4OayuUZJ3aHd7e16Q=,iv:kXBP2quRMO24nDDlNJyuXsDLPsSP9TI+hrk5t0Zc77g=,tag:lPLEDU9w3hs9xFaCm9HA0Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
