apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:HGxWVwNts8VxE5BwacgaxLQnzqFf5pabz3Fq/nM17K2KZ9K+U2+7aWghR270Ls/4sQroAQE1w0uhwoQ0AHUZzLJbbF1SqrmClHsaKmRZQuAyVUkLEDc1a/fkT7V6TkTRTFMa7S2TI9hwBE/6rD7jXXOUYbPKb6WFY52fWZm1FHn9e+mPRiun0EGbruaqJDlKfpuY/MqqjtZfdIwCC850+/CXwGDTQSt/eJPZNwihIxli0vdA5O7/YIR8gkYHlhoSlFU4YxNna1/qwzMMikelD52ef1erGH4odzpH0CF2cV9c7OlhDQnJ8qtG5+gtAJ4lrkuib/gyhV8GObbpwrEtO0w/nzH/FTBa3yNtcQ1paJanUp95AD2KlhtH8wIFyZs2,iv:FsIRQO0PKecwyHFAOa0W2A6HKo4zcQDYp+1NZrmjJmY=,tag:abmou6m0MtI7QN52qYazgw==,type:str]
    identity.pub: ENC[AES256_GCM,data:3REqzswG3hihadFcc3S2AoSPTYh0GdBwUWPlZmlYXlJgQKBV5AswN+TzpWdlh0Qzl+TSNrb2qwOBS0bA9B7XiMynHKxSSLd7VZ/U3fyDSnN5czcN5scgBDDPW7q1aK8A64HuKq5phqEBu6GcMczeV3lIgwBGq5+wiokBWGXLv+zXPyoZmxJWxEgak/IzMTuyWwNAC7H7TUbNWIFvx5h+V27+dOZGjbAr3CMlux1VpFb8WAI3J7lc9wjG5O+tCHZiYQqiwAkjsdopmtqvZw==,iv:zdUAU8sa5U4Hd41n6okwVnSvTVGHVEhM9xbWG6z1yIk=,tag:5cms3ANI5cCh81DiW8AUew==,type:str]
    known_hosts: ENC[AES256_GCM,data:jWXV0j1JRje1MbuATvmqfkV2MZ4zK9wbUuv0Bq9FxNcnM/KkRQh8njOEjDJjtW3Bvuk2KajegMjHZ3VE8dHPR0BQ20hCSbfsOCrguUsrMG+a90HSjy7cIhXkjRbkoh2PLUYza8vTA6m1ARx8EsUXEJqY964Foo8gWLOF76f08ED+RIBlxOLOWP2MUi2WmmHrZGBeSyd16i8Bkp1pjBo8jZq3fPPyXLcFGtNZ,iv:Q7wMsDjuEUSAQ7lRb2nMi7Sour4xbErAtVy2aMm9HQg=,tag:NhM3avkLnKjPmb1VQM/y1g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z324taz8q83tl3g9hpt4g6cfv7x8x90c543zj0344phevr2tdp9s9dnx6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM3YzUmtlVDlrVUpacFNZ
            bEc3cHp4eXF0VzByRDZoZXF5cWR6VE4xMHhFCkRtT2ppQnc1K1FUYjY0WW5mRzU0
            V1dOZGZJV2hOUlIwMU9FdVY1bXc1NlUKLS0tIG5VRVJkdS82T0dEVHdvejcrOUt5
            QzQyQjZzakFIVVZsT2FteDhFVWNDZXcKQx0aECctJqBaanB7nZF0bA3cQznpcJxu
            X8gJW8lB1LwrJx7+cHgsyxzWU7Sh8rzKJAYwZZLrXXbYsnUqVK35Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-09T23:35:46Z"
    mac: ENC[AES256_GCM,data:+tr9eQmKQoNH9ahAPYPfCsYiJtS99Xh6bpRojU5/Lyt/L1dWZovOeUP2OO9Q3PqgmNAa4A7P8DpNCv9uJy7fMcJYGT3Ctlsl2qwI/2Jl/8ZQJmK3Ydu+gCddMSksJvRZ0rEboP8WPFr1+Ls+iRlkW6Lib5GRR2FGyK3PoEm2Ohs=,iv:91y7PHGgdD05aEArUf0Z/o4b9+SLSBgw+6t79ak5Cs4=,tag:NPgel0gXooVjF7wzWIQRAQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
