---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hass
  namespace: hass
spec:
  interval: 15m
  chart:
    spec:
      chart: home-assistant
      version: 26.11.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-hass"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"

    homeassistant:
      trusted_proxies:
        - 172.16.0.0/16
        - 172.17.0.0/16
        - 10.1.0.0/24
        - 192.168.254.0/24

    ingress:
       main:
         enabled: true
         hosts:
           - host: hass.${DOMAIN_0}
             paths:
               - path: /
                 pathType: Prefix
         integrations:
           certManager:
             certificateIssuer: domain-0-le-prod
             enabled: true
           homepage:
             description: ""
             enabled: true
             group: Apps
             icon: ""
             name: ""
             widget:
               custom:
                 key: ""
               enabled: false
           traefik:
             allowCors: false
             enabled: true
             entrypoints:
               - websecure

    persistence:
      config:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
      backup:
        enabled: true
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
        mountPath: /config/backups

    cnpg:
      main:
        backups:
          enabled: true
          credentials: s3
        recovery:
          method: object_store
          credentials: s3