---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 15m
  chart:
    spec:
      chart: prometheus
      version: 21.2.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    TZ: Europe/Amsterdam

    ingress:
      main:
        enabled: true
        hosts:
          - host: prometheus.${DOMAIN_0}
        tls:
          - hosts:
              - prometheus.${DOMAIN_0}
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: local
                namespace: traefik
            entrypoints:
              - websecure
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod