---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unpoller
  namespace: unpoller
spec:
  interval: 15m
  chart:
    spec:
      chart: unpoller
      version: 12.7.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                UP_UNIFI_DEFAULT_URL: "${INFRA_UNIFI_URL}"
                UP_UNIFI_DEFAULT_USER: "${INFRA_UNIFI_USER}"
                UP_UNIFI_DEFAULT_PASS: "${INFRA_UNIFI_PASS}"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 10.1.0.114