apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-image-renderer
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/grafana-image-renderer/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster