apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tandoor-recipes
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/system/cloudflared/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster